name: Vault Approle Token extractor through Vault Broker API
description: Acquires a token to be used on vault through the broker API
branding:
  icon: package
  color: blue

inputs:
  ### Required
  broker_jwt:
    description: The JWT to be used on the broker
    required: true
  provision_role_id:
    description: The id of the role to be used during provisioning
    required: true
  project_name:
    description: Name of the project on vault, Ex. client
    required: true
  app_name:
    description: Name of the app on vault, Ex. app-client
    required: true
  environment:
    description: Name of the vault environment, Ex. development
    required: true

  ### Usually a bad idea / not recommended
  diff_branch:
    default: ${{ github.event.repository.default_branch }}
    description: Branch to diff against
  repository:
    default: ${{ github.repository }}
    description: Non-default repo to clone
  broker_url:
    default: https://nr-broker.apps.silver.devops.gov.bc.ca
    description: Something other than the default broker URL
  vault_addr:
    description: Something other than the default vault address
    default: https://vault-iit.apps.silver.devops.gov.bc.ca

outputs:
  vault_token:
    description: The vault token acquired by the action

runs:
  using: "node20"
  main: "index.js"

