name: Pull Request Closed

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # If merged into main, then handle any image promotions
  release:
    name: Action release
    permissions:
      contents: write
      discussions: write
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Backing up Changelog
        run: |
            mv CHANGELOG.md OLD.CHANGELOG.md
            touch CHANGELOG.md

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v5
        id: changelog
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'false'
          git-push: 'true'

      - name: Merging Changelog
        if: ${{ !steps.changelog.outputs.skipped }}
        run: |
            mv CHANGELOG.md RELEASE.md
            cat RELEASE.md OLD.CHANGELOG.md > CHANGELOG.md

      - name: Update resources
        uses: test-room-7/action-update-file@v1.8.0
        if: ${{ !steps.changelog.outputs.skipped }}
        with:
          file-path: CHANGELOG.md
          commit-msg: "doc: updating changelog"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ !steps.changelog.outputs.skipped }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  # Clean up OpenShift when PR closed, no conditions
  cleanup-openshift:
    name: Cleanup OpenShift
    env:
      name: ${{ github.event.repository.name }}-${{ github.event.number }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Remove OpenShift artifacts
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
          oc project ${{ vars.OC_NAMESPACE }}

          # If found, then remove
          helm status ${{ env.name }} && helm uninstall --no-hooks ${{ env.name }} || \
            echo "Not found: ${{ env.name }}"
